
run:
	/usr/bin/env /usr/lib/jvm/java-16-openjdk-amd64/bin/java -XX:+ShowCodeDetailsInExceptionMessages -Dfile.encoding=UTF-8 @/tmp/cp_emgf1g5macd0lkovlnf3r413n.argfile org.nypl.journalsystem.LibrarySystem
